services:
  - type: web
    name: autoqa-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 5000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
